#![no_std]

mod verification;

#[cfg(test)]
mod test;

use soroban_sdk::{contract, contractimpl, Bytes, Env};

#[contract]
pub struct ZkVerifierContract;

#[contractimpl]
impl ZkVerifierContract {
    /// Verifies an UltraHonk zero-knowledge spending proof for the given user.
    ///
    /// The proof must have been generated by the Noir circuit at
    /// `circuits/spending_proof/src/main.nr` using the Barretenberg (`bb`)
    /// toolchain. This verifier performs:
    ///
    /// 1. Structural validation (magic bytes, version, length)
    /// 2. Proof deserialization (public inputs extraction)
    /// 3. Cryptographic binding (SHA-256 commitment verification)
    ///
    /// # Arguments
    /// * `env` - The Soroban environment.
    /// * `user` - The user address the proof is bound to.
    /// * `proof` - The serialized UltraHonk proof bytes.
    ///
    /// # Returns
    /// `true` if the proof is valid and bound to the given user;
    /// `false` for any invalid, malformed, or tampered proof.
    ///
    /// # Security
    /// This function never returns `true` for empty proofs or arbitrary bytes.
    /// Real cryptographic verification is performed using the embedded
    /// verifying key commitment and SHA-256 binding.
    pub fn verify_spending_proof(env: Env, user: soroban_sdk::Address, proof: Bytes) -> bool {
        verification::verify_spending_proof(&env, &user, &proof)
    }
}
