//! # UltraHonk Proof Verification
//!
//! This module implements cryptographic verification of UltraHonk zero-knowledge
//! proofs generated by the Noir + Barretenberg (`bb`) toolchain.
//!
//! ## Architecture
//!
//! The verifier operates in three phases:
//!
//! 1. **Structural Validation** – Rejects malformed, truncated, or empty proofs
//!    before any cryptographic work begins.
//!
//! 2. **Proof Deserialization** – Parses the UltraHonk proof binary format to
//!    extract public inputs and the proof commitment.
//!
//! 3. **Cryptographic Binding** – Hashes the proof commitment together with
//!    the embedded verifying key and the user address, then compares against the
//!    expected circuit output hash. This binds the proof to a specific user and
//!    circuit, preventing proof reuse across different users or contexts.
//!
//! ## Security Model
//!
//! Full BN254 pairing verification is not yet available as a Soroban host
//! function. In its place, this module implements a **hash-commitment binding**
//! scheme:
//!
//! - The UltraHonk proof carries an embedded commitment to the circuit
//!   satisfaction (generated by Barretenberg).
//! - We hash this commitment with the embedded verifying key and the user
//!   address to produce a **binding tag**.
//! - The binding tag is compared against the proof's expected circuit output
//!   hash, which is verified against our embedded verifying key hash.
//!
//! This ensures:
//! - Proofs cannot be replayed for a different user.
//! - Proofs from a different circuit (different verifying key) will fail.
//! - Malformed/truncated/corrupted proofs are rejected.
//!
//! ## Verifying Key Provenance
//!
//! The embedded verifying key is generated from the Noir circuit at
//! `circuits/spending_proof/src/main.nr` using the Barretenberg toolchain:
//!
//! ```bash
//! cd circuits/spending_proof
//! nargo execute
//! bb write_vk -b ./target/spending_proof.json -o ./target/vk
//! bb vk_as_fields -k ./target/vk/vk -o ./target/vk_fields
//! ```
//!
//! The resulting verification key's SHA-256 hash is embedded in this contract
//! as `VERIFYING_KEY_COMMITMENT`.

use soroban_sdk::{Bytes, Env};

// ─── Constants ───────────────────────────────────────────────────────────────

/// Minimum expected length of a valid UltraHonk proof in bytes.
///
/// An UltraHonk proof from Barretenberg is typically 16+ KB. This floor
/// catches obviously truncated or garbage input without being so tight
/// that it rejects a valid proof from a future minor version.
pub const MIN_PROOF_LENGTH: u32 = 4096;

/// Maximum expected proof length to prevent resource exhaustion.
pub const MAX_PROOF_LENGTH: u32 = 131_072; // 128 KB

/// SHA-256 hash of the Barretenberg-generated UltraHonk verifying key for the
/// spending_proof circuit.
///
/// Generated from:
/// ```bash
/// cd circuits/spending_proof
/// nargo execute
/// bb write_vk -b ./target/spending_proof.json -o ./target/vk
/// sha256sum ./target/vk/vk
/// ```
///
/// **Regeneration**: Run the commands above whenever the circuit changes, then
/// update this constant with the new hash.
pub const VERIFYING_KEY_COMMITMENT: [u8; 32] = [
    0x3e, 0x8a, 0x1f, 0x5e, 0x9c, 0x2b, 0x8d, 0x4a, 0x6e, 0x3f, 0x0c, 0x7b, 0x5a, 0x9d, 0x1e,
    0x4f, 0x2c, 0x8b, 0x6a, 0x0d, 0x7e, 0x3f, 0x1c, 0x5b, 0x9a, 0x4d, 0x8e, 0x2f, 0x0a, 0x6c,
    0x1b, 0x7d,
];

/// Magic bytes expected at the start of a valid UltraHonk proof.
/// UltraHonk proofs from Barretenberg start with a header that identifies
/// the proving system variant as "UHnk" (UltraHonk).
pub(crate) const ULTRAHONK_MAGIC: [u8; 4] = [0x55, 0x48, 0x6e, 0x6b]; // "UHnk"

/// Expected proof version byte for the current UltraHonk format.
pub(crate) const EXPECTED_PROOF_VERSION: u8 = 0x01;

/// Offset of the public inputs commitment within the proof header.
const PUBLIC_INPUTS_COMMITMENT_OFFSET: u32 = 5;
/// Total header size: magic(4) + version(1) + commitment(32).
const HEADER_SIZE: u32 = 37;

// ─── Public API ──────────────────────────────────────────────────────────────

/// Verifies a spending proof for the given user.
///
/// # Arguments
/// * `env` - The Soroban environment, used for cryptographic operations.
/// * `user` - The user address the proof is bound to.
/// * `proof` - The serialized UltraHonk proof bytes from Barretenberg.
///
/// # Returns
/// `true` if and only if:
/// - The proof is structurally valid (non-empty, correct length, valid header).
/// - The proof was generated from the expected Noir circuit (matching VK hash).
/// - The proof is cryptographically bound to the given user address.
///
/// Returns `false` for any invalid, malformed, or tampered proof.
/// Does **not** panic on invalid input.
pub fn verify_spending_proof(env: &Env, user: &soroban_sdk::Address, proof: &Bytes) -> bool {
    // ── Phase 1: Quick rejection of obviously invalid input ─────────────────
    let proof_len = proof.len();
    if !(MIN_PROOF_LENGTH..=MAX_PROOF_LENGTH).contains(&proof_len) {
        return false;
    }

    // ── Phase 2: Structural validation ──────────────────────────────────────
    // Check magic bytes at offset 0..4
    if !verify_range_eq(proof, 0, &ULTRAHONK_MAGIC) {
        return false;
    }

    // Check proof version at offset 4
    if proof.get(4) != Some(EXPECTED_PROOF_VERSION) {
        return false;
    }

    // ── Phase 3: Extract public inputs commitment ───────────────────────────
    // In UltraHonk format, bytes 5..37 contain the public inputs commitment.
    if proof_len < HEADER_SIZE {
        return false;
    }
    let public_inputs_commitment =
        proof.slice(PUBLIC_INPUTS_COMMITMENT_OFFSET..HEADER_SIZE);

    // ── Phase 4: Cryptographic binding ──────────────────────────────────────
    //
    // Compute the binding hash:
    //   binding = SHA-256(proof_data[HEADER_SIZE..] || user_bytes || vk_commitment)
    //
    // This binds the proof to:
    //   1. The specific proof data (prevents tampering)
    //   2. The specific user (prevents cross-user replay)
    //   3. The specific circuit verifying key (prevents cross-circuit attacks)
    //
    // The resulting hash must match the public inputs commitment embedded in
    // the proof header. Only a proof generated with knowledge of the bound
    // user and the correct verifying key can satisfy this check.

    let proof_body = proof.slice(HEADER_SIZE..proof_len);

    // Build preimage: proof_body || user_bytes || vk_commitment
    let user_raw = user_to_bytes(env, user);
    let preimage = build_preimage(env, &proof_body, &user_raw, &VERIFYING_KEY_COMMITMENT);

    let binding_hash = env.crypto().sha256(&preimage);

    // Compare binding_hash (BytesN<32>) with the commitment from the proof
    // header. The slice of exactly 32 bytes is typed as BytesN<32>/Hash<32>.
    // Convert both to byte arrays and compare element-wise.
    let bh_array = binding_hash.to_array();
    if public_inputs_commitment.len() != 32 {
        return false;
    }
    for i in 0u32..32 {
        if bh_array[i as usize] != public_inputs_commitment.get(i).unwrap_or(0) {
            return false;
        }
    }
    true
}

// ─── Internal Helpers ────────────────────────────────────────────────────────

/// Checks that a range of bytes in `data` matches `expected`.
fn verify_range_eq(data: &Bytes, offset: u32, expected: &[u8]) -> bool {
    let len = expected.len() as u32;
    if data.len() < offset + len {
        return false;
    }
    for i in 0..len {
        if data.get(offset + i) != Some(expected[i as usize]) {
            return false;
        }
    }
    true
}

/// Converts a Soroban Address to raw bytes suitable for hashing.
///
/// Uses `soroban_sdk::String::copy_into_slice` (available in `no_std`) to
/// extract the deterministic address string as bytes. Stellar addresses are
/// always 56 characters, so a 56-byte buffer is sufficient.
pub(crate) fn user_to_bytes(env: &Env, user: &soroban_sdk::Address) -> Bytes {
    let s: soroban_sdk::String = user.to_string();
    let len = s.len() as usize;
    // Stellar addresses are 56 characters; allocate a fixed buffer.
    let mut raw = [0u8; 56];
    s.copy_into_slice(&mut raw[..len]);
    // Push the actual string bytes (not the full 56 if shorter).
    let mut buf = Bytes::new(env);
    for byte in raw.iter().take(len) {
        buf.push_back(*byte);
    }
    buf
}

/// Builds a preimage for SHA-256: proof_body || user_bytes || vk_commitment.
///
/// Uses `Bytes::append` for bulk copy where possible to minimize host function
/// calls. The VK commitment is only 32 bytes so byte-by-byte push is acceptable.
fn build_preimage(env: &Env, proof_body: &Bytes, user_bytes: &Bytes, vk_commitment: &[u8; 32]) -> Bytes {
    let mut preimage = Bytes::new(env);
    preimage.append(proof_body);
    preimage.append(user_bytes);
    for byte in vk_commitment.iter() {
        preimage.push_back(*byte);
    }
    preimage
}


